//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'java'
    // Standard Artifact Publish
    id 'maven-publish'
    id 'signing'
    id 'org.jreleaser' version '1.18.0'
    id "fabric-loom" version "1.10-SNAPSHOT" apply false
}
group = project.maven_group
version = "${project.mod_version}+${project.minecraft_version}"
if (project.hasProperty('SNAPSHOT')) {
    version = "${version}-SNAPSHOT"
}
subprojects { Project subProject ->
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)

    group = project.maven_group
    version = "${project.mod_version}+${project.minecraft_version}"
    if (project.hasProperty('SNAPSHOT')) {
        version = "${version}-SNAPSHOT"
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release.set(17)
    }

    javadoc.options.addStringOption('Xdoclint:none', '-quiet')

    jar {
        manifest {
            attributes([
                    'Specification-Title'     : archives_base_name,
                    'Specification-Vendor'    : 'The_Fireplace',
                    'Specification-Version'   : project.jar.archiveVersion,
                    'Implementation-Title'    : project.name,
                    'Implementation-Version'  : project.jar.archiveVersion,
                    'Implementation-Vendor'   : 'The_Fireplace',
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    'Timestampe'              : System.currentTimeMillis(),
                    'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                    'Build-On-Minecraft'      : minecraft_version
            ])
        }
        from('LICENSE') {
            rename { "${it}_${archives_base_name}" }
        }
    }

    repositories {
        mavenCentral()

        maven {
            name = 'Sponge / Mixin'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }

    // Disables Gradle's custom module metadata from being published to maven. The
    // metadata includes mapped dependencies which are not reasonably consumable by
    // other mod developers.
    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }

    tasks.register('copyLibs', Copy) {
        from subProject.layout.buildDirectory.dir('libs')
        into rootProject.layout.buildDirectory.dir('libs')
    }

    tasks.register('copyArtifacts', Copy) {
        from subProject.layout.buildDirectory.dir('staging-deploy')
        into rootProject.layout.buildDirectory.dir('maven/staging-deploy')
        finalizedBy(tasks.copyLibs)
    }
}

jreleaser {
    signing {
        active = 'ALWAYS'
        armored = true
        verify = false
    }
    release {
        github {
            repoOwner = 'The-Fireplace-Minecraft-Mods'
            name = 'Overlord'
            username = 'The-Fireplace'
        }
    }
    deploy {
        maven {
            mavenCentral {
                'release-deploy' {
                    active = 'RELEASE'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('build/maven/staging-deploy')
                }
            }
            nexus2 {
                'snapshot-deploy' {
                    active = 'SNAPSHOT'
                    url = 'https://central.sonatype.com/repository/maven-snapshots'
                    snapshotUrl = 'https://central.sonatype.com/repository/maven-snapshots'
                    applyMavenCentralRules = true
                    snapshotSupported = true
                    closeRepository = true
                    releaseRepository = true
                    stagingRepository('build/maven/staging-deploy')
                }
            }
        }
    }
}