name: 😃 Feature Request
description: Suggest an improvement for this mod
labels: [ enhancement ]
body:
  - type: textarea
    attributes:
      label: Description
      description: A description of the new feature or improvement you want.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        If you have any additional information, feel free to include it here.
        
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
