name: build against linux and create snapshot
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        java: [
          17,
        ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
              16
              ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: publish to aggregate build directory
        run: ./gradlew build test publish -PSNAPSHOT=true

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: Artifacts
            path: build/libs/

      - name: jreleaser release published artifacts
        run: ./gradlew jreleaserDeploy -PSNAPSHOT=true
        env:
            JRELEASER_GPG_PASSPHRASE: ${{ secrets.NEXUS_GPG_SECRET_KEY_PASSWORD }}
            JRELEASER_GPG_SECRET_KEY: ${{ secrets.NEXUS_GPG_SECRET_KEY_RING_FILE }}
            JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
            JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}

      -   name: capture JReleaser output
          if: failure()
          uses: actions/upload-artifact@v4
          with:
              name: JReleaser
              path: |
                  build/jreleaser/trace.log
                  build/jreleaser/output.properties
